
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- annotateFeatures("EDS-1014")

annotateFeatures <- function(exp, flist=NULL, debuging=FALSE) {
	servSet <- getServerSettings(debuging)
	mycon <- DBI::dbConnect(RMySQL::MySQL(), user = "public", dbname = "QueryTables", port = servSet$port, host = servSet$host, password = "public")
#         rs <- DBI::dbSendQuery(mycon, sql)
#         ar <- DBI::fetch(rs,n=-1)
        platform <- DBI::dbGetQuery(mycon, paste0("select Platform from ExperimentMetadata where Experiment='", exp , "'"))[1,1]

        if(is.null(flist)) { 
	    sql <- paste0("select ProbeGene.Probe as Probe, ProbeGene.Gene as Gene from ProbeGene ,Platforms where Platforms.Platform = '", platform,"' and ProbeGene.Platform_ID = Platforms.ID")
	} else {
	    sql <- paste0("select ProbeGene.Probe as Probe, ProbeGene.Gene as Gene from ProbeGene ,Platforms where ProbeGene.Probe in (", flist,") and Platforms.Platform = '", platform,"' and ProbeGene.Platform_ID = Platforms.ID")
	}
#         rs <- DBI::dbSendQuery(mycon, sql)
        probegene <- DBI::dbGetQuery(mycon, sql)
        DBI::dbDisconnect(mycon)
        
        colnames(probegene) <- c("PROBE", "ID_geneid")
        idname <- geneid2symbol(paste(probegene$ID_geneid, collapse=","), species="Hs", description=TRUE, debuging=debuging)
        mm <- match(probegene$ID_geneid, idname$GeneID)
        probegene$Name_GeneSymbol <- idname$Symbol[mm]
        probegene$DESCRIPTION <- idname$Description[mm]
        probegene <- probegene[,c(1,3,2,4)]
        rownames(probegene) <- probegene$PROBE
        return(probegene)
}

