
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords test
#' @export 
#' @examples
#' res <- batchTregGRS(....)

create_xls_from_eset <- function(esetName, path_to_write)
{
        sessionID <- paste(c(strsplit(date(), split=" ")[[1]], as.integer(runif(1)*10e6)),sep="",collapse="_")
        sessionID <- gsub(":", "_", sessionID)
	write("Data",file=paste(path_to_write,"download_data",sessionID,".xls",sep=""),append=TRUE)
	write.table(Biobase::exprs(esetName),file=paste(path_to_write,"download_data",sessionID,".xls",sep=""), sep="\t", quote=FALSE, row.names=TRUE, col.names=TRUE, append=TRUE)
	blankline <- "\nSample Annotations"
	write(blankline,file=paste(path_to_write,"download_data",sessionID,".xls",sep=""),append=TRUE)
	write.table(Biobase::pData(esetName),file=paste(path_to_write,"download_data",sessionID,".xls",sep=""), sep="\t", quote=FALSE, row.names=TRUE, col.names=TRUE, append=TRUE)
	return(sessionID)		

}
