
#' A function for creating KEGG hyperlinks.
#'
#' This function allows you to create many KEGG pathway hyperlincs quikly using several cores, if available.
#' @param pathwayidlist A list of all pathways needed to be used in the analysis.
#' @param topGenes A data.frame object containing geneIDs as row names, log2 fold Changes and pValue or adj_pValues for each gene.
#'	This data.frame should at least have two columns named "log2FoldChange" and "pval"/"padj".
#' @param fdr  A logical value for False Discovery Rate. If needs to be used, set to TRUE.
#' @param cutoff Significance level (alpha).
#' @param species A character string. One of c("Hs", "Mm", "Rn") for Human, Mouse or Rat pathways respectively.
#' @param foldChange A logical value if fold change is provided.
#' @param path_to_write This necessary parameter specifies the path which user wants to save the 
#'	output files (heatmaps, TreeView files and some other output files) to be saved in.
#' @param sessionID This is the sessionID generated by previous "master_LincsDataAnalysis" or "master_diffGenes" functions run.
#' @param authors M. Fazel-Najafabadi
#' @keywords KEGGlinks
#' @export 
#' @examples
#' res <- KEGGlinks(....)

## Mehdi: SPIA pathway analysis for the gene list

createKEGGlinks <- function(pathwayidlist, topGenes, fdr=FALSE, cutoff = 0.01, species = "Hs", foldChange=FALSE, 
			    path_to_write=NULL, sessionID=NULL) {
  tg <- TRUE
  if(!is.data.frame(topGenes)) {
    tg <- FALSE
    pathwayidlist <- get(data("keggPathways"))[[species]]
    
    if(length(na.omit(as.integer(topGenes))) < length(topGenes)/2) {
      data(geneinfo)
      topGenes <- na.omit(geneinfo[match(topGenes, geneinfo$Symbol),"GeneID"])
    }
    homoloArr <- getHomologousGenes(as.character(topGenes), org=species)
    topGenes <- data.frame(geneid=homoloArr$homoloGeneID[!is.na(homoloArr$homoloGeneID)], log2FoldChange=0, pval=0.05, stringsAsFactors=F)
    rownames(topGenes) <- topGenes$geneid
  }
  
  if (foldChange) {
    pvals <- -abs(topGenes$log2FoldChange)
    cutoff <- -log2(cutoff)
  } else if (fdr) {
    pvals <- p.adjust(topGenes$pval, method="fdr")
  } else {
    pvals <- topGenes$pval
  }
  na.pval <- is.na(pvals)
  pvals <- pvals[!na.pval]
  geneid <- rownames(topGenes)[!na.pval]
#  geneid <- topGenes$gid
 names(pvals) <- geneid
  log2FC <- topGenes[geneid, "log2FoldChange"]
  names(log2FC) <- geneid
  DEcol <- "red"
  notDEcol <- "black"
  notindataFG <- "gray"
  notindataBG <- "white"

  # Create blue / gray / yellow gradient
##  library(gplots)
  log2FCthresh <- 1
  nGradient <- 11
  lowBGcol <- "blue"
  midBGcol <- "#E6E6E6"  # soft gray
  hiBGcol <- "yellow"
  logFCgradient <- gplots::colorpanel(nGradient, low=lowBGcol,mid=midBGcol, high=hiBGcol)
  # Substitute "%23" instead of "#"
  logFCgradient <- gsub("#", "%23", logFCgradient)

  genecol <- data.frame(geneid=geneid, row.names=geneid)
  genecol$fg <- ifelse(pvals < cutoff, DEcol, notDEcol)
  index <- pmax(1, pmin(nGradient, floor(1 + (log2FC + log2FCthresh) * (nGradient - 2) / (2 * log2FCthresh)) + 1))
  genecol$bg <- logFCgradient[index]
  if(species == "Hs") {
    species <- "hsa"
  } else if (species == "Mm") {
    species <- "mmu"
  } else if (species == "Rn") {
    species <- "rno"
  }
  if(tg & all(substr(pathwayidlist, 1, 3) != species)) {
    stop("Wrong pathwayidlist format!")
#     pathwayidlist <- paste0(species, pathwayidlist)
  }


  keggPaths <- get(load(paste0("keggPathways_", species, ".rda")))
  if(!tg) {
    res <- data.frame(Nam = pathwayidlist, 
		      ID = names(pathwayidlist), 
		      pSize = sapply(keggPaths, function(j) length(j[[1]]$GENE)/2), 
		      NDE = sapply(keggPaths, function(j) sum(j[[1]]$GENE %in% as.character(topGenes$geneid))), 
		      KEGGLINK = NA, 
		      Remark = NA, stringsAsFactors = FALSE)
    res <- res[res$NDE > 0, ]
    pathwayidlist <- res$ID
  }
  
  keggPaths <- keggPaths[pathwayidlist]
  KEGGlinks <- NULL
  for(pathway in pathwayidlist) {
    which.path <- which(sapply(keggPaths, function(i) i[[1]]$ENTRY)==pathway)
    kegg.path <- keggPaths[[which.path]][[1]]
    path.genes <- kegg.path$GENE
    path.genes.df <- data.frame(matrix(path.genes, ncol=2, byrow=TRUE))
    colnames(path.genes.df) <- c("geneid", "description")
    path.genes.df$geneid <- as.character(path.genes.df$geneid)
    rownames(path.genes.df) <- path.genes.df$geneid
    path.genes.df$keggid <- sub(".*?KO:(.*?)(].*|$)", "\\1", path.genes.df$description)
    keggid.table <- table(path.genes.df$keggid)
    path.genes.df$duplicate <- keggid.table[path.genes.df$keggid] > 1
    
    unique.geneid <- path.genes.df$geneid[!path.genes.df$duplicate]
    overlap.geneid <- intersect(unique.geneid, geneid)
    missing.geneid <- unique.geneid[!(unique.geneid %in% geneid)]
    pathway.genecol <- genecol[overlap.geneid, ]
    pathway.genecol[missing.geneid, "fg"] <- notindataFG
    pathway.genecol[missing.geneid, "bg"] <- notindataBG
    pathway.genecol$geneid <- rownames(pathway.genecol)
    duplicate.geneid <- path.genes.df$geneid[path.genes.df$duplicate]
    duplicate.keggid <- unique(path.genes.df[duplicate.geneid, "keggid"])
    for(dd in duplicate.keggid) {
      dup.path.genes <- path.genes.df[path.genes.df$keggid == dd, "geneid"]
      overlap.dup.geneid <- intersect(dup.path.genes, geneid)
      pathway.genecol[dup.path.genes[1], "geneid"] <- dup.path.genes[1]
      if(length(overlap.dup.geneid) == 0) {
        pathway.genecol[dup.path.genes[1], "fg"] <- notindataFG
        pathway.genecol[dup.path.genes[1], "bg"] <- notindataBG
      } else {
        if(any(pvals[overlap.dup.geneid] < cutoff)) {
          pathway.genecol[dup.path.genes[1], "fg"] <- DEcol
        } else {
          pathway.genecol[dup.path.genes[1], "fg"] <- notDEcol
        }
        
        max.log2FC <- max(log2FC[overlap.dup.geneid])
        min.log2FC <- min(log2FC[overlap.dup.geneid])
        dup.log2FC <- ifelse(abs(max.log2FC) > abs(min.log2FC), max.log2FC, min.log2FC)
        # Find corresponding log2FC color gradient index
        dup.index <- max(1, min(nGradient, floor(1 + (dup.log2FC + log2FCthresh) * (nGradient - 2) / (2 * log2FCthresh)) + 1))
        pathway.genecol[dup.path.genes[1], "bg"] <- logFCgradient[dup.index]
      }
    }
    urlbegin <- paste0("http://www.kegg.jp/kegg-bin/show_pathway?map=", pathway, "&multi_query=")
    newlink <- urlbegin
    # Create link text for first gene, then loop through the remaining genes with "%0D%0A" between each one
    gene.text <- paste0(pathway.genecol[1, "geneid"], "+", pathway.genecol[1, "bg"], "%2C", pathway.genecol[1, "fg"])
    newlink <- paste0(newlink, gene.text)
    for(gg in pathway.genecol$geneid[-1]) {
      gene.text <- paste0(gg, "+", pathway.genecol[gg, "bg"], "%2C", pathway.genecol[gg, "fg"])
      newlink <- paste0(newlink, "%0D%0A", gene.text)
    }
    KEGGlinks <- c(KEGGlinks, newlink)
  }#, mc.cores=10)
  
  if(!tg) {
    res$KEGGLINK <- KEGGlinks
    res$Remark <- "Done"
    colnames(res) <- c("KEGG pathway name", "KEGG pathway ID", "Genes in Pathway", "Found Genes in Pathway", "KEGG link", "Remark")
    return(res) 
  } else return(KEGGlinks)
}

