
#' A function for ...
#'
#' This function allows you to ...
#' @param sessionID sessionID generated by previous step of analysis.
#' @param geneID Any single gene Entrez ID to create scatter plot.
#' @param path_to_write This parameter specifies the path which user wants to save the results.
#' @param output Any of "json" or "widget" formats for the plot.
#' @param debuging This is for database testing purposes only. The default database server used in all work flows is "eh3" but it can be set to 
#'	alternative database server "gimm2" if debuging=TRUE dev servers will be used.
#' @param authors M. Fazel-Najafabadi
#' @keywords filter
#' @export
#' @examples
#' ## Do not run
#' sessionID <- "Fri_Oct_5_13_16_50_2018_4925482"
#' geneID <- "2099"
#' path_to_write <- "/mnt/raid/tmp/"
#' plt <- genePlot(sessionID, geneID, prop="ER", path_to_write, output="json", debuging=TRUE)
#' ## End do not run


genePlot <- function(sessionID, geneID, prop, path_to_write="/mnt/raid/tmp/", output="json", fontSize=13)# dotSize=0.7,
{

if(is.null(sessionID)) return("Missing sessionID!")
if(is.null(geneID)) return("Missing Entrez gene ID!")

a <- Sys.time()
print(paste("genePlot called with following parameters at:",a))
print(paste("sessionID: ", sessionID))
print(paste("gene Entrez ID: ", geneID))
print(paste("path_to_write:", path_to_write))
eset <- try(get(load(paste0(path_to_write, "filteredeset_", sessionID, ".RData"))))
if(class(eset) != "ExpressionSet") return("No appropriate input file or path!")
fdat <- Biobase::fData(eset)
fdat <- fdat[fdat$ID_geneid == geneID,]
if(dim(fdat)[1] == 0) return("Gene not found!")
edat <- Biobase::exprs(eset)
edat <- edat[rownames(fdat),,drop=FALSE]
edat <- colMeans(edat)
dat <- Biobase::pData(eset)
dat <- dat[, prop, drop=FALSE]
dat <- cbind.data.frame(dat, Value_LogDiffExp=edat)
dat[,1] <- as.character(dat[,1])
dat$Sample <- names(edat)
if(output %in% c("json", "widget")) { # | dim(dat)[1] <= 1000) {
    plt <- ggplot2::ggplot(dat, ggplot2::aes_(x=as.name(colnames(dat)[1]), y=as.name(colnames(dat)[2]), label=as.name(colnames(dat)[3]), fill=as.name(colnames(dat)[1]))) + 
	    ggplot2::geom_boxplot(outlier.shape = NA) + 
	    ggplot2::ylab("logDiffExp") +
	    ggplot2::theme_bw() +
	    ggplot2::geom_jitter(shape=16, position = ggplot2::position_jitter(0.2)) +
	    ggplot2::theme(text = ggplot2::element_text(size = fontSize), axis.text = ggplot2::element_text(size = fontSize))
    plt <- plotly::ggplotly(plt)
    if (output=="json") return(plotly::plotly_json(plt, FALSE))
    if(output=="widget") htmlwidgets::saveWidget(plt, "genePlot.html", selfcontained = TRUE) # if(sigID == "LINCSCP_109") 
    return(plt)
} else {
    b <- Sys.time()
    print(paste("plotting done in",b-a))
    pdffile <- paste0(path_to_write, sessionID, ".pdf")
    pdf(pdffile)
    boxplot(x = dat, xlab="Samples", ylab=fdat$Name_GeneSymbol, main="Value_LogDiffExp")
    dev.off()
    return(pdffile)
}
}

