
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

get_nbr_data <- function(nbr=NULL,exp=NULL){
	findcdt <- NULL
	findcdt <- paste("ls /data/srv/www/htdocs/BreastCancer/cdt/*.cdt|grep ",exp)
	cdtfile <- system(findcdt,intern=TRUE)
	colnames <- paste("head -n 1 ",cdtfile)
	cols <- system(colnames,intern=TRUE)
	cols <- strsplit(cols,"\t")
	cdtData <- NULL
	for(a in nbr){
		command <- paste("awk '{if ($2==",a,") print $0}' ",cdtfile)
		s <- system(command,intern=TRUE)
			if(length(s)!=0){
				row <- strsplit(s,"\t")
				cdtData <- rbind(cdtData,t(data.frame(row)))
			}
		s <- NULL
	}
	colnames(cdtData)<-cols[[1]]
	return(cdtData)
}
