
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

get_feature_dataframe <- function(db,feature, debuging=FALSE){
	servSet <- getServerSettings(debuging)
	mycon <- DBI::dbConnect(RMySQL::MySQL(), user = "public", dbname = db, port = servSet$port, host = servSet$host, password = "public")
#        if (!test) {
#	  mycon <- DBI::dbConnect(RMySQL::MySQL(), user='public', dbname=db, port = 4040,host="10.165.4.231", password='public')}
#	else {
#	  mycon <- DBI::dbConnect(RMySQL::MySQL(), user='public', dbname=db, host="gimm2.ketl.uc.edu", password='public')}
        df <- NULL
	s <- NULL
        for(a in feature)
        {
                if(is.null(s))
                {
                        s<-paste("'",a,"'",sep="")
                } else {
                        s<-paste(s,",'",a,"'",sep="")
                }

        }

	sql <- paste("select Name,ID from Feature where ID in (",s,")",sep="")
	rs <- DBI::dbSendQuery(mycon, sql)
	df <- DBI::fetch(rs,n=-1)
	DBI::dbDisconnect(mycon)
        return(df)
}
