
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

get_sample_properties <- function(db,exp,meas_limits, debuging=FALSE){
	servSet <- getServerSettings(debuging)
	mycon <- DBI::dbConnect(RMySQL::MySQL(), user = "public", dbname = db, port = servSet$port, host = servSet$host, password = "public")
#        if (!test) {
#	  mycon <- DBI::dbConnect(RMySQL::MySQL(), user='public', dbname=db, host="10.165.4.231", port = 4040, password='public')}
#	else {
#	  mycon <- DBI::dbConnect(RMySQL::MySQL(), user='public', dbname=db, host="gimm2.ketl.uc.edu", password='public')}
	#mycon <- DBI::dbConnect(RMySQL::MySQL(), user="public", dbname=platform, host="db2.ketl.uc.edu", port = 3306, password="public")
        sampledata <- NULL
        t <- NULL
        for(m in meas_limits[[1]]:meas_limits[[2]]){
        if(is.null(t)) {
                         t<-m
                 } else {
                         t <- paste(t,",",m,sep="")
                 }
        }
	F <- "select S.Name,A.Value,M.ID from Sample S, AttributeText A, Measurement M where M.ID in ("
	F1 <- ") and M.Name = S.Name and S.Attributes_ID=A.ID"
	Fsql <- paste(F,t,F1,sep="")
	rsSampleData <- DBI::dbSendQuery(mycon, Fsql)
	sdata <- DBI::fetch(rsSampleData,n=-1)
	sampledata <- rbind(sampledata,data.frame(sdata))

        DBI::dbDisconnect(mycon)
        return(sampledata)
}
