
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

get_genes_from_genelist <- function(listname,table, debuging=FALSE)
{
##        library(RMySQL)
	servSet <- getServerSettings(debuging)
	mycon <- DBI::dbConnect(RMySQL::MySQL(), user = "public", dbname = "GeneDistance", port = servSet$port, host = servSet$host, password = "public")
#        if (!test) {
#	  mycon <- DBI::dbConnect(RMySQL::MySQL(), user='public', dbname="GeneDistance", port = 4040,host="10.165.4.231", password='public')}
#	else {
#	  mycon <- DBI::dbConnect(RMySQL::MySQL(), user='public', dbname="GeneDistance", host="gimm2.ketl.uc.edu", password='public')}
        sql <- paste("select List from ",table," where Name = '",listname ,"'",sep="")
        rs <- DBI:dbSendQuery(mycon, sql)
        genesdf <- DBI::fetch(rs, n = -1)
        genes <- genesdf[1,1]

        genes <- gsub(":",",",genes)
        genes <- gsub("NA,","",genes)
        genes <- gsub(",NA","",genes)
        sql <- paste("select GeneID,Symbol,description from GeneDB.GeneInfo where GeneID in (",genes,")",sep="")
        rs <- DBI::dbSendQuery(mycon, sql)
        geneInfo <- DBI::fetch(rs,n=-1)
        DBI::dbDisconnect(mycon)
        return(geneInfo)
}
