
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

getDefaultErrorDataframe <- function(newRemark){
	#remark<-"Filtered zero"
	remark <- newRemark		##1
	gpgene <- "NA"			##2
	gpprobe <- "NA"			##3
	dc2 <- "NA"			##4
	pkeggvalue <- "NA"		##5
	filteredSamples <- "NA"		##6
	sessionID <- "NA"		##7
	pvalueLR <- "NA"		##8
	noOfGenes <- "NA"		##9
	noOfProbes <- "NA"		##9+1
	coeffs <- "NA"			##10+1
	coeffsGeneID <- "NA"		##11+1
	coeffsGeneName <- "NA"		##12+1
	sample_after_filtering <- 0	##13+1
	filteredSamples <- "NA"		##14+1
	tableNames <- "NA"		##15+1
	cc <- "NA"			##16+1
	corTablePath <- "NA"		##17+1
	level1 <- "NA"			##18+1
	level2 <- "NA"			##19+1
	Pvals <- "NA"			##20+1
	x <- data.frame(sessionID,gpgene,gpprobe,dc2,pkeggvalue,remark,sample_after_filtering,filteredSamples,pvalueLR,noOfGenes,noOfProbes,coeffs,coeffsGeneID,coeffsGeneName,level1,level2,Pvals,tableNames,cc,corTablePath)
	colnames(x) <- c("sessionID","gpgene","gpprobe","dc2","pkeggvalue","Remark","sample_after_filtering","FilteredSamples","pvalueLR","NoOfGenes","NoOfProbes","coefficients","coefficientsGeneID","coefficientsGeneName","level1","level2","Pvals","tableNames","cc","corTablePath")
	return(x)
}
