
#' A function for ...
#'
#' This function allows you to ...
#' @param sessionID sessionID generated by previous step of analysis.
#' @param path_to_write This parameter specifies the path which user wants to save the results.
#' @param authors M. Fazel-Najafabadi
#' @keywords filter
#' @export
#' @examples
#' ## Do not run
#' sessionID <- "Fri_Oct_5_13_16_50_2018_4925482"
#' path_to_write <- "/mnt/raid/tmp/"
#' allprop <- getProp(sessionID, path_to_write)
#' ## End do not run


getProp <- function(sessionID, path_to_write="/mnt/raid/tmp/")
{

if(is.null(sessionID)) return("Missing sessionID!")
eset <- try(get(load(paste0(path_to_write, "filteredeset_", sessionID, ".RData"))))
if(class(eset) != "ExpressionSet") return("No appropriate input file or path!")
return(colnames(Biobase::pData(eset)))
	
}

