
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)


getpData <- function(exp, db=NULL, debuging=FALSE) {
	servSet <- getServerSettings(debuging=debuging)
	mycon <- DBI::dbConnect(RMySQL::MySQL(), user = "public", dbname = "QueryTables", port = servSet$port, host = servSet$host, password = "public")
	tmp <- DBI::dbGetQuery(mycon, paste0("SELECT * FROM MeasurementMetadata WHERE Experiment = '", exp, "'"))
	tmp <- tmp[, c("Measurement_ID", "MeasurementName", "sortingOrder", "PropertyName", "PropertyValue")]
	if(all(!is.null(tmp$sortingOrder))) {
	    ord <- unique(tmp[,c("sortingOrder", "PropertyName")])
	    ord <- ord[order(ord$sortingOrder),]
	    tmp <- reshape2::recast(tmp, MeasurementName~PropertyName, measure.var='PropertyValue')
	    tmp <- tmp[, c("MeasurementName", ord$PropertyName)]
	} else {
	    tmp <- reshape2::recast(tmp, MeasurementName~PropertyName, measure.var='PropertyValue')
	}
	return(tmp)
}
