
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

getTopGenes <- function(data, NoofGenes, libName) {
  allGenes <- NULL
  for (i in 1:dim(data)[2]) {
    if (libName[i] == "LIB_3") {
      data[, i] <- 1 - data[, i]
    }  # encode
    ord <- order(data[, i])
    allGenes <- c(allGenes, (rownames(data)[ord])[1:NoofGenes])
  }
  allGenes <- unique(allGenes)
  allGenes <- na.omit(allGenes)
  return(allGenes)
}
