
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

myAllez <- function(scores, geneList, categoryList) {
	geneList <- geneList[!is.na(scores)]
        scores <- scores[!is.na(scores)]
	categoryList <- unique(categoryList)
	index <- na.omit(match(categoryList, geneList))
	m <- length(index)
	if (m > 0) {
		G <- length(scores)
		xBar <- mean(scores[index], na.rm = TRUE)
		mu <- mean(scores, na.rm = TRUE)
		sigma <- sqrt((sum(scores^2, na.rm = TRUE)/G - mu^2) * (G - m)/(G - 1)/m)
		c(n.genes = m, zScore = (xBar - mu)/sigma)
	} else {
		c(n.genes = 0, zScore = NA)
	}		
}
