
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

parse_sample_properties <- function(propertyTags){
        parsedSD <- strsplit(propertyTags[,2],";")
        parsedSD <- data.frame(parsedSD)
        parsedSD1 <- apply(parsedSD,1,function(x) strsplit(x,"="))
        dataTable <- list(SampleID=propertyTags[,1])
        cnames <- c("SampleID")
        for(i in 1:length(parsedSD1)){
          cnames <- c(cnames,unlist(parsedSD1[[i]][[2]][1]))
          cValues <- unlist(lapply(parsedSD1[[i]],function(x) {
                if (length(x)==2) toRet<-x[[2]]
                else toRet <- NA
                toRet}))
          dataTable <- c(dataTable,list(cValues))
        }
        dataTable <- data.frame(dataTable)
	dataTable <- cbind(dataTable,propertyTags[,3])
        colnames(dataTable) <- c(cnames,"MeasurementIDs")
	rownames(dataTable) <- propertyTags[,1]
        return(dataTable)
}
