
#' A function to parse the results from previos analysis and turn it to a data table
#'
#' This function allows you to parse the results from previos analysis generated by "master_LincsDataAnalysis" or "master_diffGenes" functions.
#' @param res The input value which is in the form of a data frame generated by previous functions.
#' @param path_to_write This optional parameter specifies the path to save the parsed results in the form of ".txt" and ".RData" files.
#' @param write write argument is used to save the SignatureTable for further uses.
#'	 It should be set to TRUE, as it is by default, to save the SignatureTable otherwise no table will be saved. 
#' @param Value The output of this function is in the form of a data.frame. First column is geneIDs, second column is geneNames, 
#'	third column is coefficients and the last column is their probability values for each gene from statistical analysis (ttest).
#' @param authors M. Fazel-Najafabadi
#' @keywords SignatureTable.
#' @export 
#' @examples
#' ## not run
#' sigTable <- parse_res(res)
#' ## end not run

parse_res <- function(res, path_to_write=NULL, write=TRUE) {
    if (res$coefficientsGeneID != "NA" & res$coefficients != "NA" & res$Pvals != "NA"){# & res$gpnames != "NA") {
        
        GeneID <- unlist(strsplit(res$coefficientsGeneID, split = "DELIM"))
#        GeneID <- as.vector(GeneID[[1]])
        
        GeneNames <- unlist(strsplit(res$coefficientsGeneName, split = "DELIM"))
#        GeneNames <- as.vector(GeneNames[[1]])
        
        coefficients <- as.numeric(unlist(strsplit(res$coefficients, split = "DELIM")))
#        coefficients <- as.vector(coefficients[[1]])
#        coefficients <- as.numeric(coefficients)
        
        Pvals <- as.numeric(unlist(strsplit(res$Pvals, split = "DELIM")))
#        Pvals <- as.vector(Pvals[[1]])
#        Pvals <- as.numeric(Pvals)
        
        SignatureTable <- data.frame(GeneID, GeneNames, coefficients, Pvals, stringsAsFactors = F)
	colnames(SignatureTable) <- c("ID_geneid", "Name_GeneSymbol", "Value_LogDiffExp", "Significance_pvalue")
#        SignatureTable <- SignatureTable[complete.cases(SignatureTable), ]
        volcano_name <- paste(path_to_write,"temp_volcanoOld_", as.character(res[[1]]), ".RData", sep = "")
        volcano_name2 <- paste(path_to_write,"temp_volcanoOld_", as.character(res[[1]]), ".xls", sep = "")
        if (write) {
# 		colnames(SignatureTable) <- c("ID_geneid", "Name_GeneSymbol", "Value_LogDiffExp", "Significance_pvalue")
		write.table(SignatureTable, file = volcano_name2, row.names=FALSE, sep="\t", quote=FALSE)
		write.table(SignatureTable, file = sub("temp_volcanoOld_", "completeSigOld_", volcano_name2), row.names=FALSE, sep="\t", quote=FALSE)
		save(SignatureTable, file = volcano_name)
	}
    return(SignatureTable)
    }
}
