
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

plot_features_without_properties <- function(dframe,sessionID,web=FALSE){
	allColors <- c("blue","red","green","yellow","purple","brown","black","blue4","red4","green4","yellow4")
	pal <- marray::maPalette(low="blue",high="yellow",mid="black")
	pdf(paste("/data/srv/www/htdocs/tmp/woprop",sessionID,".pdf",sep=""),height=max(5,0.07*(100)))

	if(dim(dframe)[2]==1){
		plot(1:dim(dframe)[1],as.numeric(unlist(dframe[,1])),pch=19,col=allColors[1],xlab="Samples",ylab="Gene Expression Level")
	} else {
		gplots::heatmap.2(data.matrix(t(dframe)),trace="none",col=pal,labCol=NA)
	}
	try(dev.off())
        cat(paste("<p><a href=\"http://eh3.uc.edu/tmp/woprop",sessionID,".pdf\"> Plot without property</a></p>",sep=""))
}
