
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export
#' @examples
#' res <- batchTregGRS(....)

runilincsSPIA <- function (de, all, pathwaySetName, ...) {

requirePkg <- function (name) {
    if (!requireNamespace(name, quietly = TRUE))
        stop("library ", name, " is missing", call. = FALSE)
}

checkPkgVersion <- function (name, min_version) {
    version <- package_version(installed.packages()[name, "Version"])
    if (version < package_version(min_version))
        stop("the installed ", name, " version is too old (need at least ",
            min_version, ")", call. = FALSE)
}

datasetName <- function (pathwaySetName) paste(pathwaySetName, "SPIA.RData", sep = "")

    requirePkg("SPIA")
    checkPkgVersion("SPIA", "2.18")
    if (!(datasetName(pathwaySetName) %in% dir())) 
        stop("There is no dataset corresponding to the pathway set name: ", 
            pathwaySetName, "\n", "Did you forget to run prepareSPIA?")
    optArgs <- list(...)
    if (!is.null(optArgs$organism)) 
        warning("Ignoring the \"organism\" parameter.")
    if (!is.null(optArgs$data.dir)) 
        warning("Ignoring the \"data.dir\" parameter.")
    optArgs$organism <- pathwaySetName
    optArgs$data.dir <- paste0(dirname(pathwaySetName), "/")
    do.call("ilincsSPIA", c(list(de, all), optArgs), envir=.GlobalEnv)[, c(-2, -12)]
}
