
#' A function for ...
#'
#' This function allows you to ...
#' @param query.p ...
#' @param reference.p ...
#' @param query.gL ...
#' @param reference.gL ...
#' @param na.rm ...
#' @param estimateNullDistr ...
#' @param nullDistrQuantiles ...
#' @param nullDistrN ...
#' @param tolerateWarnings ...
#' @param pAdjust.method.query ...
#' @param pAdjust.method.reference ...
#' @param lambda ...
#' @param rescale ...
#' @param plotRescaled ...
#' @param multicoreN ...
#' @param authors M. Fazel-Najafabadi
#' @keywords ...
#' @export 
#' @examples
#' res <- batchTregGRS(....)

write_fitered_eset <- function(esetName,samples,db,exp,path_to_write)
{
	tmpeset <- load(paste(path_to_write,esetName,".RData",sep=""))
	samples <- as.character(samples)
	sampleNames <- unlist(strsplit(samples,","))
##	library(Biobase)
	esetName <- get(tmpeset)
	newExprs <- Biobase::exprs(esetName)[,sampleNames, drop=FALSE]
	newpData <- Biobase::pData(esetName)[sampleNames,, drop=FALSE]
	newfData <- Biobase::fData(esetName)[,, drop=FALSE]
# 	if(is.vector(newExprs)) newExprs <- t(data.frame(newExprs))
# 	if(is.vector(newfData)) newfData <- t(data.frame(newfData))
	newesetName <- paste(exp, "_", db, "_", paste(unlist(strsplit(gsub(":", " ", date()), " ") ), collapse="_", sep=""), sep="")
	assign(newesetName, new("ExpressionSet", exprs=newExprs, phenoData=new("AnnotatedDataFrame", data=newpData), 
						 featureData=new("AnnotatedDataFrame", data=newfData)))
# 	assign(newesetName, new("ExpressionSet", exprs=as.matrix(newExprs), phenoData=new("AnnotatedDataFrame", data=as.data.frame(newpData, stringsAsFactors=FALSE)), 
# 						 featureData=new("AnnotatedDataFrame", data=as.data.frame(newfData, stringsAsFactors=FALSE))))
	save(list=newesetName, file=paste(path_to_write, newesetName, ".RData",sep=""))
	return(newesetName)
}
